import { Session } from "@/components/cards/SessionCard";

export const MOCK_SESSIONS: Session[] = [
  {
    id: "1",
    title: "Jehan Session",
    instructor: "Jehan Doe",
    location: "Room 101",
    timeStart: "09:00 AM",
    timeEnd: "10:30 AM",
    status: "action-now",
    role: "Attendee",
    idBadge: "#101",
    date: "Today",
    attendance: null,
  },
  {
    id: "2",
    title: "Alfred Session",
    instructor: "Alfred Smith",
    location: "Room 202",
    timeStart: "11:00 AM",
    timeEnd: "12:00 PM",
    status: "upcoming",
    role: "Attendee",
    idBadge: "#102",
    date: "Tomorrow",
    attendance: null,
  },
  {
    id: "3",
    title: "Evening Review",
    instructor: "Evening Lead",
    location: "Room 303",
    timeStart: "04:00 PM",
    timeEnd: "05:00 PM",
    status: "completed",
    role: "Superuser",
    idBadge: "#103",
    date: "Yesterday",
    attendance: "Present",
  },
  {
    id: "4",
    title: "Morning Sync",
    instructor: "Team Lead",
    location: "Online",
    timeStart: "08:00 AM",
    timeEnd: "09:00 AM",
    status: "missed",
    role: "Attendee",
    idBadge: "#104",
    date: "Yesterday",
    attendance: "Missed",
  },
  {
    id: "5",
    title: "Weekly Planning",
    instructor: "Jane Doe",
    location: "Room 105",
    timeStart: "02:00 PM",
    timeEnd: "03:00 PM",
    status: "upcoming",
    role: "Attendee",
    idBadge: "#105",
    date: "Tomorrow",
    attendance: null,
  },
];